version: "3.9"
services:
  mongodb:
    image : mongo
    container_name: mongodb_project_gallery_me
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./docker-service-volumes/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  aws:
    hostname: minio
    image: quay.io/minio/minio
    container_name: minio_project_gallery_me
    command: server /data --console-address :9001
    environment:
        MINIO_ROOT_USER: minio
        MINIO_ROOT_PASSWORD: minio123
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
        interval: 30s
        timeout: 20s
        retries: 3
    volumes:
        - ./docker-service-volumes/storage/data:/data
    ports:
          - "9000:9000"
          - "9001:9001"
    restart: unless-stopped
