'use client';

export {
	ArrowLeftCircleIcon as ArrowLeftCircleIcon,
	ArrowLeftIcon as ArrowLeftIcon,
	ArrowLeftIcon as BackIcon,
	ArrowLeftOnRectangleIcon as LoginIcon,
	ArrowRightCircleIcon as ArrowRightCircleIcon,
	ArrowRightIcon as ArrowRightIcon,
	ArrowRightOnRectangleIcon as LogoutIcon,
	ArrowUpIcon as ArrowUpIcon,
	ArrowUpTrayIcon as FileUploadIcon,
	Bars3Icon as MenuIcon,
	BookmarkIcon as FavoriteIcon,
	CameraIcon as AddAPhotoIcon,
	CheckIcon as ConfirmIcon,
	CheckIcon as SaveIcon,
	ChevronDownIcon as ArrowDownIcon,
	ChevronDownIcon as ExpandMoreIcon,
	ChevronRightIcon as SubMenuIcon,
	ChevronUpIcon as ExpandLessIcon,
	Cog6ToothIcon as SettingsIcon,
	EllipsisHorizontalIcon as MoreIcon,
	FolderIcon as GalleriesIcon,
	HomeIcon as HomeIcon,
	InformationCircleIcon as InfoIcon,
	NewspaperIcon as BlogIcon,
	NewspaperIcon as JournalIcon,
	PaperClipIcon as AttachmentIcon,
	PencilIcon as EditIcon,
	PlusIcon as AddIcon,
	ShareIcon as ShareIcon,
	TrashIcon as DeleteIcon,
	UserIcon as ProfileIcon,
	UserPlusIcon as RegisterIcon,
	WrenchScrewdriverIcon as ProjectIcon,
	XCircleIcon as CancelIcon,
	XMarkIcon as CloseIcon,

	// one-offs
	CheckCircleIcon as PositiveBulletIcon,
} from '@heroicons/react/24/outline';

export {
	BookmarkIcon as FavoriteActiveIcon,
	Cog6ToothIcon as SettingsActiveIcon,
	FolderIcon as GalleriesActiveIcon,
	HomeIcon as HomeActiveIcon,
	NewspaperIcon as JournalActiveIcon,
	UserIcon as ProfileActiveIcon,
} from '@heroicons/react/24/solid';
